###
# This is the place to override the gearmand cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "gearmand/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the gearmand max connections:
#
#normal[:gearmand][:port] = "8192"
